version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1383gh
      POSTGRES_DB: clinic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
