# Generated by Django 5.1.4 on 2024-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_otpmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
