# Generated by Django 5.1.2 on 2024-11-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='doctor',
        ),
    ]
