# Generated by Django 5.1.4 on 2024-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_otpmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
