# Generated by Django 5.1.2 on 2024-11-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_rename_user_user_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doctor',
        ),
    ]
