# Generated by Django 5.1.2 on 2024-12-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_addressmodel_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='user',
        ),
    ]
