# Generated by Django 5.1.2 on 2024-11-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
        ('Home', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_about', to='Home.image'),
        ),
    ]
