# Generated by Django 5.1.2 on 2024-11-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_aboutusmodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='images',
        ),
    ]
