# Generated by Django 5.1.2 on 2024-11-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=True)),
                ('type', models.CharField(choices=[('doctor', 'Doctor'), ('about', 'About')], default='doctor', max_length=150)),
            ],
        ),
    ]
