# Generated by Django 5.1.2 on 2024-11-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_aboutusmodel_images'),
        ('Home', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
