# Generated by Django 5.1.2 on 2024-11-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_remove_aboutusmodel_images'),
        ('Home', '0003_rename_image_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_about', to='AboutUs.aboutusmodel'),
        ),
    ]
