# Generated by Django 5.1.4 on 2025-01-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_aboutusmodel_imagemodel_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
