# Generated by Django 5.1.2 on 2024-12-05 07:24

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='department/')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('landline_phone', models.CharField(max_length=11, null=True)),
                ('medical_license_number', models.CharField(max_length=5, null=True)),
                ('bio', models.TextField(null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_department_doctor', to='Doctor.doctordepartmentmodel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=155)),
                ('issuing_institution', models.CharField(max_length=255)),
                ('date_issue', django_jalali.db.models.jDateField()),
                ('expiration_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('additional_details', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_doctor', to='Doctor.doctormodel')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointment', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointment', to='Doctor.doctormodel')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, null=True)),
                ('graduation_year', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('academic_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_to_education', to='Doctor.academicfieldmodel')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_education', to='Doctor.doctormodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSpecialtyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_medical_special', to='Doctor.doctordepartmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsMedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', django_jalali.db.models.jDateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_medical_specialty', to='Doctor.doctormodel')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Details_Medical_Specialty_related', to='Doctor.medicalspecialtymodel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('5', 'شنبه'), ('6', 'یکشنبه'), ('0', 'دوشنبه'), ('1', 'سه شنبه'), ('2', 'چهارشنبه'), ('3', 'پنجشنبه'), ('4', 'جمعه')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_working_hours', to='Doctor.doctormodel')),
            ],
        ),
    ]
