# Generated by Django 5.1.2 on 2024-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='department',
        ),
    ]
