# Generated by Django 5.1.2 on 2024-11-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_departmentmodel_delete_department'),
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorModel',
        ),
    ]
