# Generated by Django 5.1.2 on 2024-11-03 06:32

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0003_alter_user_birthday'),
        ('Doctor', '0002_delete_doctormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
            ],
            options={
                'abstract': False,
            },
            bases=('Accounts.user',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
