# Generated by Django 5.1.4 on 2025-02-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_remove_doctormodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
