# Generated by Django 5.1.4 on 2025-03-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_workinghourmodel_add_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghourmodel',
            name='delete_record',
        ),
    ]
