# Generated by Django 5.1.2 on 2024-11-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_remove_departmentmodel_doctors'),
        ('Doctor', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorModel',
        ),
    ]
