# Generated by Django 5.1.4 on 2025-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_remove_workinghourmodel_delete_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghourmodel',
            name='delete_record',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'accepted'), ('WAITING', 'waiting'), ('NOT_ACCEPTED', 'not accepted')], default='ACCEPTED', null=True),
        ),
    ]
