# Generated by Django 5.1.4 on 2025-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_workinghourmodel_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghourmodel',
            name='day',
            field=models.CharField(choices=[('1', 'شنبه'), ('2', 'یکشنبه'), ('3', 'دوشنبه'), ('4', 'سه شنبه'), ('5', 'چهارشنبه'), ('6', 'پنجشنبه'), ('7', 'جمعه')], max_length=15),
        ),
        migrations.AlterField(
            model_name='workinghourmodel',
            name='delete_record',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'accepted'), ('WAITING', 'waiting'), ('NOT_ACCEPTED', 'not accepted')], default='NOT_ACCEPTED', null=True),
        ),
    ]
