# Generated by Django 5.1.4 on 2025-07-19 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_alter_workinghourmodel_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
