# Generated by Django 5.1.2 on 2024-11-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='user',
        ),
    ]
