# Generated by Django 5.1.2 on 2024-11-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_remove_doctormodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorModel',
        ),
    ]
