# Generated by Django 5.1.4 on 2025-07-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_appointmentmodel_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient/qr_codes/'),
        ),
    ]
