# Generated by Django 5.1.2 on 2024-11-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_doctormodel_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='landline_phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='medical_license_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='EducationDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_to_education', to='Doctor.academicfieldmodel')),
            ],
        ),
    ]
