# Generated by Django 5.1.2 on 2024-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_academicfieldmodel_doctormodel_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetailsmodel',
            name='university',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
