# Generated by Django 5.1.2 on 2024-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_educationdetailsmodel_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetailsmodel',
            name='country',
            field=models.CharField(choices=[], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='educationdetailsmodel',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
    ]
