# Generated by Django 5.1.2 on 2024-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0019_educationdetailsmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetailsmodel',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
