# Generated by Django 5.1.2 on 2024-11-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0021_remove_educationdetailsmodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetailsmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_education', to='Doctor.doctormodel'),
        ),
    ]
