# Generated by Django 5.1.2 on 2024-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_educationdetailsmodel_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetailsmodel',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
