# Generated by Django 5.1.2 on 2024-11-15 07:08

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0023_educationdetailsmodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=155)),
                ('issuing_institution', models.CharField(max_length=255)),
                ('date_issue', django_jalali.db.models.jDateField()),
                ('expiration_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('additional_details', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_doctor', to='Doctor.doctormodel')),
            ],
        ),
    ]
