# Generated by Django 5.1.2 on 2024-11-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0009_remove_departmentmodel_doctors'),
        ('Doctor', '0024_certificatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialtyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_medical_special', to='Department.departmentmodel')),
            ],
        ),
    ]
