# Generated by Django 5.1.2 on 2024-11-16 07:46

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0025_medicalspecialtymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsMedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', django_jalali.db.models.jDateField()),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_medical_specialty', to='Doctor.doctormodel')),
                ('specialty', models.ManyToManyField(related_name='Details_Medical_Specialty_related', to='Doctor.medicalspecialtymodel')),
            ],
        ),
    ]
