# Generated by Django 5.1.2 on 2024-11-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0027_alter_detailsmedicalspecialty_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsmedicalspecialty',
            name='specialty',
        ),
    ]
