# Generated by Django 5.1.2 on 2024-11-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0028_remove_detailsmedicalspecialty_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmedicalspecialty',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Details_Medical_Specialty_related', to='Doctor.medicalspecialtymodel'),
        ),
    ]
