# Generated by Django 5.1.2 on 2024-11-22 06:01

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0029_detailsmedicalspecialty_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAYS', models.CharField(choices=[('SATURDAY', 'شنبه'), ('SUNDAY', 'یکشنبه'), ('MONDAY', 'دوشنبه'), ('TUESDAY', 'سه شنبه'), ('WEDNESDAY', 'چهارشنبه'), ('THURSDAY', 'پنجشنبه'), ('FRIDAY', 'جمعه')], default='SATURDAY', max_length=100)),
                ('start', django_jalali.db.models.jDateField()),
                ('end', django_jalali.db.models.jDateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
