# Generated by Django 5.1.2 on 2024-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0029_detailsmedicalspecialty_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='DAYS',
            field=models.CharField(choices=[('SATURDAY', 'شنبه'), ('SUNDAY', 'یکشنبه'), ('MONDAY', 'دوشنبه'), ('TUESDAY', 'سه شنبه'), ('WEDNESDAY', 'چهارشنبه'), ('THURSDAY', 'پنجشنبه'), ('FRIDAY', 'جمعه')], default='SATURDAY', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
