# Generated by Django 5.1.2 on 2024-11-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0030_workinghourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghourmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_working_hours', to='Doctor.doctormodel'),
        ),
    ]
