# Generated by Django 5.1.2 on 2024-11-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0031_rename_days_doctormodel_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='days',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='end',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='start',
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointment', to='Doctor.doctormodel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SATURDAY', 'شنبه'), ('SUNDAY', 'یکشنبه'), ('MONDAY', 'دوشنبه'), ('TUESDAY', 'سه شنبه'), ('WEDNESDAY', 'چهارشنبه'), ('THURSDAY', 'پنجشنبه'), ('FRIDAY', 'جمعه')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_working_hours', to='Doctor.doctormodel')),
            ],
        ),
    ]
