# Generated by Django 5.1.2 on 2024-11-24 06:25

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0032_remove_doctormodel_days_remove_doctormodel_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
