# Generated by Django 5.1.2 on 2024-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0033_appointmentmodel_date_appointmentmodel_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghourmodel',
            name='day',
            field=models.CharField(choices=[('5', 'شنبه'), ('6', 'یکشنبه'), ('0', 'دوشنبه'), ('1', 'سه شنبه'), ('2', 'چهارشنبه'), ('3', 'پنجشنبه'), ('4', 'جمعه')], max_length=15),
        ),
    ]
