# Generated by Django 5.1.2 on 2024-11-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_departmentmodel_delete_department'),
        ('Doctor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_doctors', to='Doctor.doctormodel'),
        ),
    ]
