# Generated by Django 5.1.2 on 2024-11-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_departmentmodel_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='doctors',
        ),
    ]
