# Generated by Django 5.1.2 on 2024-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0007_departmentmodel_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
    ]
