# Generated by Django 5.1.2 on 2024-11-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0008_alter_departmentmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='doctors',
        ),
    ]
