# Generated by Django 5.1.2 on 2024-11-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0009_remove_departmentmodel_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
